# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-01 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180301_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
